// data/tourData.js
export const tours = [
  {
    id: 1,
    title: "12 Day Beijing to Shanghai Discovery",
    image: "/images/all-img/trip-1.jpg",
    rating: 4.3,
    reviewCount: 86,
    tripType: "Family Trip",
    tourType: "Private Tour",
    price: 2707,
    isNew: false,
    lifestyle: "Culture and lifestyle",
    activity: "Leisure walking",
  },
  {
    id: 2,
    title: "14 Day China And Pingyao Tour",
    image: "/images/all-img/trip-2.jpg",
    rating: 4.3,
    reviewCount: 86,
    tripType: "Family Trip",
    tourType: "Private Tour",
    price: 2850,
    isNew: true,
    lifestyle: "Culture and lifestyle",
    activity: "Leisure walking",
  },
  {
    id: 3,
    title: "12 Day China Highlights",
    image: "/images/all-img/trip-3.jpg",
    rating: 4.5,
    reviewCount: 92,
    tripType: "Family Trip",
    tourType: "Private Tour",
    price: 2600,
    isNew: true,
    lifestyle: "Culture and lifestyle",
    activity: "Leisure walking",
  },
  {
    id: 4,
    title: "The Cultural Essential China Travel",
    image: "/images/all-img/trip-4.jpg",
    rating: 4.8,
    reviewCount: 105,
    tripType: "Family Trip",
    tourType: "Private Tour",
    price: 3100,
    isNew: false,
    lifestyle: "Culture and lifestyle",
    activity: "Leisure walking",
  },
  {
    id: 5,
    title: "Great Family Tour with Shaolin Kung Fu !",
    image: "/images/all-img/trip-5.jpg",
    rating: 4.9,
    reviewCount: 120,
    tripType: "Family Trip",
    tourType: "Private Tour",
    price: 3250,
    isNew: true,
    lifestyle: "Culture and lifestyle",
    activity: "Leisure walking",
  },
];